### ISSUE TITLE
Implement Script

### ISSUE THREAD

**Issue by LeoNero** [hachi-bitto/btc-wallet#4]
I suggest implementing only conversion from hex to a stack-representation, and from the stack-representation to hex. There's no need to check if the execution of the stack is valid or not.

There's no need to implement the `disabled` opcodes.

For example:
```rust
let script_example = vec![
    OP_DUP,
    OP_HASH160,
    VALUE(404371705fa9bd789a2fcd52d2c580b65d35549d),
];

script_example.to_hex();
```

We can also implement this part as a macro:
```rust
let script_example = script!(
    OP_DUP OP_HASH160 404371705fa9bd789a2fcd52d2c580b65d35549d
);
```

And also:
```rust
let hex_example = vec![0x76, 0xa9, 0x404371705fa9bd789a2fcd52d2c580b65d35549d]; // the last element would probably be split into several bytes
assert_eq!(hex_example.to_script(), script_example);
```

References:
[https://en.bitcoin.it/wiki/Script](https://en.bitcoin.it/wiki/Script)

**Comment by evaporei** [comment]
Seems good, also the macro example, I would leave that for later because it's probably more annoying/hard to do.

**Comment by LeoNero** [comment]
Yea, leaving the macro for later makes sense, but it would be cool to practice Rust macros, which I've never coded before.

Also, the code in the issue is almost just pseudocode, it will probably be different when actually implemented.
